### PR TITLE
maintain consistent alignment

### PR DESCRIPTION
**Pull request by jh-bate**
@jebeck should maintain alignment

 - no data
 - differing values (e.g 10.2 U vs 100.2 U)

### CODE REVIEW

**Comment by jh-bate** [comment]
[<ux:1 dev:3 tst:1> [basics] [data viz] show average carbs](https://trello.com/c/lGQn1UkG/59-ux-1-dev-3-tst-1-basics-data-viz-show-average-carbs)

**Comment by jh-bate** [comment]
[<ux:1 dev:3 tst:1> [basics] [data viz] show average carbs](https://trello.com/c/lGQn1UkG/59-ux-1-dev-3-tst-1-basics-data-viz-show-average-carbs)

**Comment by jebeck** [comment]
The grams value for avg carbs isn't quite aligned:
screenshot 2016-12-06 15 20 22

Changing the `padding-right` from 20px to 18px as so should do it:
screenshot 2016-12-06 15 14 24

**Comment by jh-bate** [comment]
try that @jebeck

**Pull request merged**
