### PR TITLE
Gordyd/timechange marker

### PR DESCRIPTION
**Pull request by GordyD**
screen shot 2015-08-13 at 11 52 41

@skrugman

Here is the PR for showing timeChange events complete with:

icon
hover over tool tip
The text in the tool tip currently contains the following:

classification:
Clock Drift Adjustment (if time difference is less than 8 minutes)
Time Change (all other changes)
from time
to time
From and to times are either of the following formats:

1:00 am, 4:00 pm (if both times are on same day)
1st Jan 1:00am, 3rd Feb 3:16 pm (if spread across different days, or months)
1st Jan 2014 1:00am, 3rd Feb 2015 3:16 pm (if spread across different years)

### CODE REVIEW

**Comment by darinkrauss** [comment]
@skrugman @jebeck Is there a date standard we use for Blip?  I notice the date along the top of the Daily view is "July 7", but the format for the time change tooltip is "3rd Feb 2015 3:16pm"?  Should that be "February 3, 2015 3:16pm?"  Or are we doing this to shorten the tooltip?

**Comment by skrugman** [comment]
I don't see where your talking about. Screen shot?

*Sara Krugman *
Design lead

*Tidepool *An open source, not-for-profit effort to build an open data
platform and better applications that reduce the burden of Type 1 Diabetes
and accelerate the commercialization of closed-loop systems.


*Twitter : *@skrugman
*Phone :* 617 549 1483
*Email : *sara@tidepool.org
*Web : *Tidepool.org <http://tidepool.org/>

**Comment by darinkrauss** [comment]
The top of the Daily View:

dailyview

and Gordon's comments in the  PR (above):

prcomments

**Comment by GordyD** [comment]
To be honest I hadn't though about the consistency there! This can all be
changed to align with the date format used in the header if desired...

**Comment by GordyD** [comment]
Updated branch to conform to style guidelines set out by @skrugman

Also comments from @darinkrauss have been taken on board and the formatting of date strings is now consistent with the formats used in the Header. Thanks Darin :)

The tooltips will break on to two lines if the time change spreads across different dates.

screen shot 2015-08-14 at 11 07 01
screen shot 2015-08-14 at 11 11 42

**Comment by jebeck** [comment]
Copying this comment over from the closed PR:

I do think we should add a comma in the date format though (e.g., "Aug 2, 3:19 pm"), the date and time are so squished together, or it almost looks like "Aug 23:19 pm":
screenshot 2015-08-20 12 21 10

**Pull request closed without merging**
