### PR TITLE
Data paging

### PR DESCRIPTION
**Pull request by cbwebdevelopment**
See https://trello.com/c/jmYSnJCw for full details.

Goes hand in hand with:
https://github.com/tidepool-org/blip/pull/465
https://github.com/tidepool-org/viz/pull/99
https://github.com/tidepool-org/platform-client/pull/86

This PR is primarily and update to the `tidelineData` preprocessing util, allowing data to be added/processed after the initial processing occurs.

### CODE REVIEW

**Comment by cbwebdevelopment** [comment]
[Tidepool Web - Data Paging](https://trello.com/c/jmYSnJCw/292-tidepool-web-data-paging)

**Comment by cbwebdevelopment** [comment]
[Bolus tooltips are displaying below the basal rates in Daily view](https://trello.com/c/MI81nZVi/344-bolus-tooltips-are-displaying-below-the-basal-rates-in-daily-view)

**Comment by cbwebdevelopment** [comment]
@krystophv I've pushed a fix for the bolus tooltip positioning in commit d98e046.  Would you be able to have a look?

**Comment by krystophv** [comment]
@cbwebdevelopment Yeah, that seems to be the generally accepted way of getting the offset. 👍

**Pull request merged**
