### PR TITLE
[WEB-3070] Loop in web feedback updates

### PR DESCRIPTION
**Pull request by clintonium-119**
[WEB-3070]

Related PRs:
https://github.com/tidepool-org/blip/pull/1427
https://github.com/tidepool-org/viz/pull/401

[WEB-3070]: https://tidepool.atlassian.net/browse/WEB-3070?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by krystophv — APPROVED** [review]
LGTM 🚀

**Review by krystophv — CHANGES_REQUESTED** [review]
Actually, looks like the unit test needs an update :/

**Comment by clintonium-119** [comment]
Good call.  Fixed.

**Review by krystophv — APPROVED** [review]
LGTM 🚢

**Pull request merged**
