### PR TITLE
Gordyd/timechange marker

### PR DESCRIPTION
**Pull request by GordyD**
screen shot 2015-08-13 at 11 52 41
@skrugman 

Here is the PR for showing timeChange events complete with:
 - icon
 - hover over tool tip

The text in the tool tip currently contains the following:

 - classification: 
     - Clock Drift Adjustment (if time difference is less than 8 minutes)
     - Time Change (all other changes)
 - from time 
 - to time

From and to times are either of the following formats:
 - 1:00 am, 4:00 pm (if both times are on same day)
 - 1st Jan 1:00am, 3rd Feb 3:16 pm (if spread across different days, or months)
 - 1st Jan 2014 1:00am, 3rd Feb 2015 3:16 pm (if spread across different years)

### CODE REVIEW

**Comment by jebeck** [comment]
PR against jebeck/bootstrap-utc please.

**Comment by skrugman** [comment]
Nice! Text needs more padding in the tool tip and tooltip box opacity
should be .6

*Sara Krugman *
Design lead

*Tidepool *An open source, not-for-profit effort to build an open data
platform and better applications that reduce the burden of Type 1 Diabetes
and accelerate the commercialization of closed-loop systems.


*Twitter : *@skrugman
*Phone :* 617 549 1483
*Email : *sara@tidepool.org
*Web : *Tidepool.org <http://tidepool.org/>

**Comment by brandonarbiter** [comment]
After testing bootstrapping last night, I realize that it's important to
include the date. If someone changes the time from 4am to 8pm, which
direction did they go? @jebeck do you agree? if so, @skrugman, do you want
to suggest how that might look?

**Comment by brandonarbiter** [comment]
Woops, disregard. Darin beat me to it!!! Woot!

**Comment by jebeck** [comment]
I do think we should add a comma in the date format though (e.g., "Aug 2, 3:19 pm"), the date and time are so squished together, or it almost looks like "Aug 23:19 pm":
screenshot 2015-08-20 12 21 10

**Comment by skrugman** [comment]
I agree with Jana

*Sara Krugman *
Design lead

*Tidepool *An open source, not-for-profit effort to build an open data
platform and better applications that reduce the burden of Type 1 Diabetes
and accelerate the commercialization of closed-loop systems.


*Twitter : *@skrugman
*Phone :* 617 549 1483
*Email : *sara@tidepool.org
*Web : *Tidepool.org <http://tidepool.org/>

**Pull request closed without merging**
