### PR TITLE
Update Mocha link

### PR DESCRIPTION
**Pull request by mortonfox**

### CODE REVIEW

**Comment by jebeck** [comment]
Hi @mortonfox, sorry for the slow response here. Thanks for this change!

Hopefully this next request isn't too onerous - could you please update this branch with a merge from master (first `git pull origin master` in your local fork, then checkout your `patch-1` and `git merge master` - apologies if this is already familiar and I'm over-explaining...).

Then could you also follow the instructions [here](http://developer.tidepool.io/contributors/) to agree to our [Volunteer/Contributor License Agreement](http://developer.tidepool.io/files/TidepoolVCLA.pdf)? We need that as well before we can merge (but you only have to do it once!)

If you're interested in Tidepool's data visualization code, just FYI this repository is slowly going to be deprecated in favor of [viz](https://github.com/tidepool-org/viz).

**Comment by mortonfox** [comment]
I agree to the terms of Tidepool Project’s Volunteer/Contributor License Agreement v1.0 as it exists at http://tidepool-org.github.io/files/TidepoolVCLA.pdf on March 1, 2017.

**Comment by mortonfox** [comment]
And also, I've merged the upstream master into patch-1.

**Comment by jebeck** [comment]
Thanks!

**Pull request merged**
