### PR TITLE
tooltip for messages

### PR DESCRIPTION
**Pull request by GordyD**
@skrugman 

Like the other tooltip branches this branch is still a work in progress until the styling is provided. Right now, it is temporary.

### CODE REVIEW

**Comment by skrugman** [comment]
Tool tip styling is here -
https://www.pixelapse.com/tidepool/projects/Blip/Elements%20of%20data%20viz's/Tools%20tips/2015-08-13%20tool%20tip%20style.sketch

*Sara Krugman *
Design lead

*Tidepool *An open source, not-for-profit effort to build an open data
platform and better applications that reduce the burden of Type 1 Diabetes
and accelerate the commercialization of closed-loop systems.


*Twitter : *@skrugman
*Phone :* 617 549 1483
*Email : *sara@tidepool.org
*Web : *Tidepool.org <http://tidepool.org/>

**Comment by GordyD** [comment]
Awesome thank you!

**Comment by GordyD** [comment]
Updated with folllowing style...
screen shot 2015-08-14 at 14 54 06
screen shot 2015-08-14 at 15 11 07

**Comment by skrugman** [comment]
"at" (and all other secondary info) should be light grey and not bold

*Sara Krugman *
Design lead

*Tidepool *An open source, not-for-profit effort to build an open data
platform and better applications that reduce the burden of Type 1 Diabetes
and accelerate the commercialization of closed-loop systems.


*Twitter : *@skrugman
*Phone :* 617 549 1483
*Email : *sara@tidepool.org
*Web : *Tidepool.org <http://tidepool.org/>

**Comment by GordyD** [comment]
ok

**Comment by GordyD** [comment]
screen shot 2015-08-14 at 15 16 39

**Comment by skrugman** [comment]
thanks!

*Sara Krugman *
Design lead

*Tidepool *An open source, not-for-profit effort to build an open data
platform and better applications that reduce the burden of Type 1 Diabetes
and accelerate the commercialization of closed-loop systems.


*Twitter : *@skrugman
*Phone :* 617 549 1483
*Email : *sara@tidepool.org
*Web : *Tidepool.org <http://tidepool.org/>

**Comment by skrugman** [comment]
great!

*Sara Krugman *
Design lead

*Tidepool *An open source, not-for-profit effort to build an open data
platform and better applications that reduce the burden of Type 1 Diabetes
and accelerate the commercialization of closed-loop systems.


*Twitter : *@skrugman
*Phone :* 617 549 1483
*Email : *sara@tidepool.org
*Web : *Tidepool.org <http://tidepool.org/>

**Comment by jh-bate** [comment]
@GordyD  so LGTM assuming the use of moment is legit here (and from what I recall @jebeck saying thats how we do it in tideline).

FYI excited about getting this one out the door!

**Pull request closed without merging**
